---
# defaults file for instance

# This specifies what the role should do; the choices are
#
#   create: creates the instance
#   start: starts the instance
#   stop: stops the instance
#   delete: deletes the instance

azure_instance_operation: ""

######## These are the same variables used by the environ role - start ########

# Azure credential information

########azure_subscription_id: ""
########azure_client_id: ""
########azure_secret: ""
########azure_tenant_id: ""
########azure_resourcegroup: ""

# This is used to prefix several of the Azure resource names (see below).

########azure_resource_name_prefix: az

# Azure network information

########azure_virtnetwork: "{{ azure_resource_name_prefix }}-virtnet"

########azure_subnet: "{{ azure_resource_name_prefix }}-subnet"

######## These are the same variables used by the environ role - end ########

azure_linux_ansible_user: azureuser

azure_windows_ansible_user: azureuser
azure_windows_ansible_password: ""

azure_ssh_public_key_file: "path-to/id_rsa.pub"
azure_ssh_keypair_key_data: "{{ lookup('file', azure_ssh_public_key_file) }}"
azure_ssh_public_key_list:
  - path: "/home/{{ azure_linux_ansible_user }}/.ssh/authorized_keys"
    key_data: "{{ azure_ssh_keypair_key_data }}"

# Sample Linux instance

#file_scoped_basename: mylinuxsvr

#azure_instance:
#  azure_tags:
#    instance_hvar_os_type: Linux
#    instance_hvar_basename: "{{ file_scoped_basename }}"
#    instance_hvar_infra_provider: azure
#    instance_hvar_define_hostname: true
#    instance_hvar_update_etchosts_localhost: false
#    instance_hvars_inventory_groups: az_aap
#  name: "{{ azure_resource_name_prefix }}-{{ file_scoped_basename }}"
#  resource_group: "{{ azure_resourcegroup }}"
#  os_disk_size_gb: 64
#  vm_size: Standard_A1_v2
#  admin_username: "{{ azure_linux_ansible_user }}"
#  ssh_password_enabled: false
#  ssh_public_keys: "{{ azure_ssh_public_key_list }}"
#  image:
#    offer: RHEL
#    publisher: RedHat
#    sku: '8-LVM'
#    version: "8.6.2022051813"
#  network_interfaces:
#    - name: "{{ azure_resource_name_prefix }}-{{ file_scoped_basename }}-nic1"
#      ip_configurations:
#        - name: "{{ azure_resource_name_prefix }}-{{ file_scoped_basename }}-nic1"
#          primary: True
#          public_ip_address_name: "{{ azure_resource_name_prefix }}-{{ file_scoped_basename }}-nic1-public_ip"
#          public_ip_allocation_method: Static

# Sample Windows instance

#file_scoped_basename: mylinuxsvr

#azure_instance:
#  azure_tags:
#    instance_hvar_os_type: Windows
#    instance_hvar_basename: "{{ file_scoped_basename }}"
#    instance_hvar_infra_provider: azure
#    instance_hvar_define_hostname: true
#    instance_hvar_update_etchosts_localhost: false
#    instance_hvars_inventory_groups: az_aap
#  name: "{{ azure_instance_annotated_name }}"
#  resource_group: "{{ azure_resourcegroup }}"
#  os_disk_size_gb: 128
#  vm_size: Standard_A1_v2
#  admin_username: "{{ azure_windows_ansible_user }}"
#  ssh_password_enabled: false
#  image:
#    offer: "WindowsServer"
#    publisher: "MicrosoftWindowsServer"
#    sku: "2019-Datacenter"
#    version: latest
#  network_interfaces:
#    - name: "{{ azure_resource_name_prefix }}-{{ file_scoped_basename }}-nic1"
#      ip_configurations:
#        - name: "{{ azure_resource_name_prefix }}-{{ file_scoped_basename }}-nic1"
#          primary: True
#          public_ip_address_name: "{{ azure_resource_name_prefix }}-{{ file_scoped_basename }}-nic1-public_ip"
#          public_ip_allocation_method: Static
