---
# defaults file for environ

# Azure credential information

azure_subscription_id: ""
azure_client_id: ""
azure_password: ""
azure_tenant_id: ""
azure_resourcegroup: ""

# Azure location

azure_location: "eastus"

# This specifies what the role should do; the choices are
#
#   create: creates the environment
#   delete: deletes the environment

azure_env_operation: ""

# This is used to prefix several of the Azure resource names (see below).

azure_base_name: az

# Azure network information

azure_virtnetwork: "{{ azure_base_name }}-virtnet"
azure_virtnetwork_prefixes: "10.0.0.0/16"

azure_subnet: "{{ azure_base_name }}-subnet"
azure_subnet_prefix: "10.0.1.0/24"

# This defines the security group rules to be applied.

azure_securitygroup: "{{ azure_base_name }}-networksecuritygroup"
azure_securitygroup_rules:
  - name: SSH
    protocol: Tcp
    destination_port_range: 22
    access: Allow
    priority: 1001
    direction: Inbound
  - name: WinRM-HTTPS
    protocol: Tcp
    destination_port_range: 5986
    access: Allow
    priority: 1004
    direction: Inbound
